name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: ["opened", "synchronize", "reopened"]
  create:

jobs:
  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install deps
        run: pip install -r requirements_dev.txt
      - name: Unit tests
        run: pytest -v tests/test_unit.py

  tests-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install deps
        run: pip install -r requirements_dev.txt
      - name: Pull conkodi container image
        run: podman pull quay.io/quarck/conkodi:19
      - name: Pull mockserver container image
        run: podman pull docker.io/mockserver/mockserver:mockserver-5.11.2
      - name: Set permissions
        run: sudo chmod -R a+rwx tests/data
      - name: Integration tests
        run: pytest -v -k "(not test_unit)"
      - name: Kodi logs analysis
        if: failure()
        run: podman logs kodi
      - name: Mockserver logs analysis
        if: failure()
        run: podman logs mockserver
