name: deploy

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Fix permissions
        run: chmod -R a+rw ${PWD}
      - name: Build an addon
        env:
          VERSION: ${{ github.ref_name }}
        run: make video_addon
      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: make deploy
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: video.kino.pub-${{ github.ref_name }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true
